config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'articles#index'
  get '/categories/:id', to: 'categories#show', as: 'category'
  get '/articles/new', to: 'articles#new'
  post 'categories/:id', to: 'votes#create'
  resources :articles

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories, foreign_key: :article_id
  has_many :votes, foreign_key: :article_id
  has_one_attached :image

  def self.most_pop
    @arr = []
    @votes = Vote.all
    @votes.each do |vote|
      @arr << vote.article.id
    end
    @pop = @arr.max_by { |i| @arr.count(i) }
    @most_popular_article2 = Article.where('(id = ?)', @pop).first
    @most_popular_article2
  end

  scope :most_popular_article2, -> { where('(id = ?)', @most_popular_article).first }
  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  scope :tesla, -> { where('category_id = ?', 1).order(created_at: :desc) }
  scope :ford, -> { where('category_id = ?', 2).order(created_at: :desc) }
  scope :gm, -> { where('category_id = ?', 3).order(created_at: :desc) }
  scope :lucid, -> { where('category_id = ?', 4).order(created_at: :desc) }
  scope :battery, -> { where('category_id = ?', 5).order(created_at: :desc) }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def show; end

  def new
    @article = Article.new
  end

  def index
    @recent_tesla_article = Article.all.tesla.first
    @recent_ford_article = Article.all.ford.first
    @recent_gm_article = Article.all.gm.first
    @recent_lucid_article = Article.all.lucid.first
    @most_popular_article2 = Article.most_pop

    @art = Article.all
  end

  def edit
    @article.image.attach(params[:image])
  end

  def create
    @article = Article.new(article_params)
    @article2 = Article.all

    respond_to do |format|
      if @article.save
        format.html { redirect_to root_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :story, :image, :user_id, :category_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def tse(art)
    @pet_e = ''
    if art.errors.any?
      @pet_e += "<div id='error_explanation'>"
      @pet_e += "    <h2><%= pluralize(article.errors.count, 'error') %> prohibited this article from being saved:</h2>"

      @pet_e += '    <ul>'
      @pet_e += '       <%=article.errors.each do |error|%>'
      @pet_e += '        <li><%= error.full_message</li>'
      @pet_e += '      <%= end %>'
      @pet_e += '    </ul>'
      @pet_e += '</div>'
    end
    @pet_e.html_safe
  end
end

app/views/articles/_form.html.erb
<div class="card  card1 mb-3" style="max-width: 80rem; height: 32rem; margin: auto;">
  <div class="card-header card-header1 bg-transparent ">WRITE A NEW ARTICLE</div>
  <%= form_with(model: article) do |form| %>
    <%= tse(article)%>
  
    <div class="mb-3">
      <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control'  %>
    </div>
  
    <div class="mb-3">
      <%= form.label :story, class: 'form-label' %>
      <%= form.text_area :story, class: 'form-control' %>
    </div>
  
    <div class="mb-3">
      <%= form.label :Image, class: 'form-label' %>
      <%= form.file_field :image, class: 'form-control' %>
    </div>
  
    <div class="mb-3">
    <%= form.hidden_field :user_id, :value => current_user.id %>
    </div>
  
    <div class="mb-3">
      <%= form.label :category, class: 'form-label' %></br>
      <%= form.select :category_id, [['tesla', 1], ['ford', 2], ['gm', 3], ['lucid', 4]], class: 'form-control' %>
    </div>
  
    <div class="mb-3">
      <%= form.label :Date, class: 'form-label' %>
      <%= form.date_select :createdAt, class: 'form-control' %>
    </div>
  
    <div class="actions">
      <%= form.submit class: 'btn btn-info', styel: 'align: center;'%> 
    </div>

  <%end%>
</div>

app/views/articles/index.html.erb
<div class="main_img_div" style='height: 600px; width: 100%;'><%=image_tag(@most_popular_article2.image, style: 'height: 58%; width: 100%; object-fit: cover;',class: 'ctg-image ctg-img_1')%></div>
<p style="color: orange; z-index: 2; position: absolute; bottom: 350px; left: 110px;"><%= link_to @most_popular_article2.title, category_path(@most_popular_article2.category_id),  style: 'z-index: 2; position: absolute; color: orange; left: -90px; text-decoration: none;' %></a></p>
<p style="color: white; z-index: 2; position: absolute; bottom: 300px; left: 20px;"><%= @most_popular_article2.story %></p>
</div>



<div class="grid-container g3">
  <div class="grid-item">
  <span style="z-index: 2; position: absolute; color: white; left: 20px; border-bottom: 3px solid yellow;">
  <%= link_to @recent_tesla_article.title, category_path(@recent_tesla_article.category_id), class: 'art_link' %></span>
  <p class="welcome_text">
  <%= @recent_tesla_article.story %></p>
  <%=image_tag(@recent_tesla_article.image, class: 'ctg-image ctg-img_1', style: ' height: 100%; width: 100%; object-fit: cover;')%>
  </div>

  <div class="grid-item">
  <span style="z-index: 2; position: absolute; color: white;  border-bottom: 3px solid yellow; text-decoraiton: none">
  <%= link_to @recent_ford_article.title, category_path(@recent_ford_article.category_id), class: 'art_link' %></span>
  <p class="welcome_text">
  <%= @recent_ford_article.story %></p>
  <%=image_tag(@recent_ford_article.image, class: 'ctg-image ctg-img_1', style: ' height: 100%; width: 100%; object-fit: cover;')%>
  </div>

  <div class="grid-item">
  <span style="z-index: 2; position: absolute; color: white;  border-bottom: 3px solid yellow; text-decoraiton: none">
  <%= link_to @recent_gm_article.title, category_path(@recent_gm_article.category_id), class: 'art_link' %></span>
  <p class="welcome_text">
  <%= @recent_gm_article.story%></p>
  <%=image_tag(@recent_gm_article.image, class: 'ctg-image ctg-img_1', style: ' height: 100%; width: 100%; object-fit: cover;')%>
  </div>

  <div class="grid-item">
  <span style="z-index: 2; position: absolute; color: white;  border-bottom: 3px solid yellow; text-decoraiton: none">
  <%= link_to @recent_lucid_article.title, category_path(@recent_lucid_article.category_id), class: 'art_link' %></span>
  <p class="welcome_text">
  <%= @recent_lucid_article.story%></p>
  <%=image_tag(@recent_lucid_article.image, class: 'ctg-image ctg-img_1', style: ' height: 100%; width: 100%; object-fit: cover;')%>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>